# Syntax: https://docs.github.com/en/actions/reference/workflow-syntax-for-github-actions
# .NET CLI: https://docs.microsoft.com/dotnet/core/tools/
# Description: The purpose of this workflow is to compile and run unit tests.

name: Build And Test, SHIM

on:
  workflow_dispatch:
  push:
    branches: [ "main", "develop", "master" ]
  pull_request:
    branches: [ "main", "develop", "master" ]

jobs:
  build-test-SHIM:

    runs-on: ${{ matrix.os }}

    env:
      TEST_RESULTS_DIRECTORY: ${{ github.workspace }}/TestResults

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        framework: [net8.0, net9.0, net10.0, net462, net472, net480, net481]
        exclude:
          # .NET Framework doesn't run on Linux
          - os: ubuntu-latest
            framework: net462
          - os: ubuntu-latest
            framework: net472
          - os: ubuntu-latest
            framework: net480
          - os: ubuntu-latest
            framework: net481
        include: 
          - os: ubuntu-latest
            args: "--filter TestCategory!=WindowsOnly"
            solution: ./Everything.Linux.slnf
          - os: windows-latest
            solution: ./Everything.Windows.slnf

    steps:
    - uses: actions/checkout@v6
    
    - name: Setup dotnet
      uses: actions/setup-dotnet@v5.1.0
      with:
        dotnet-version: |
            3.1.x
            6.0.x
            7.0.x
            8.0.x
            9.0.x
            10.0.x

    - name: Restore
      run: dotnet restore ${{ matrix.solution }}

    - name: Build
      run: dotnet build ${{ matrix.solution }} --configuration Release --no-restore

    - name: Test
      id: test1
      continue-on-error: true
      run: dotnet test ${{ matrix.solution }} --framework ${{ matrix.framework }} --configuration Release --no-build --results-directory ${{ env.TEST_RESULTS_DIRECTORY }} --logger:"console;verbosity=detailed" --logger:"trx;logfileprefix=testResults_" ${{ matrix.args }}

    - name: Retry tests
      if: steps.test1.outcome=='failure'
      run: pwsh -f ./.scripts/build_RetryTests.ps1 -TestResultsDirectory ${{ env.TEST_RESULTS_DIRECTORY }} -WorkingDirectory ${{ github.workspace }}
